const PIC = (seed) => `https://picsum.photos/seed/${seed}/300/300`;

export const productsData = [
  // ============ MAROLIO ============
  {
    id: 1,
    nombre: "Aceite de Girasol Marolio 1.5L",
    precio: 2800,
    precioOferta: 2100,
    emoji: "🫙",
    imagen: PIC("aceite-marolio"),
    categoria: "Almacén",
    marca: "Marolio",
    destacado: true,
  },
  {
    id: 2,
    nombre: "Fideos Spaghetti Marolio 500g",
    precio: 850,
    precioOferta: 640,
    emoji: "🍝",
    imagen: PIC("fideos-marolio"),
    categoria: "Almacén",
    marca: "Marolio",
    destacado: false,
  },
  {
    id: 3,
    nombre: "Atún Marolio al Natural x3 Latas",
    precio: 2800,
    precioOferta: 2100,
    emoji: "🐟",
    imagen: PIC("atun-marolio"),
    categoria: "Almacén",
    marca: "Marolio",
    destacado: false,
  },
  {
    id: 4,
    nombre: "Sal Fina Marolio 1kg",
    precio: 650,
    precioOferta: 490,
    emoji: "🧂",
    imagen: PIC("sal-marolio"),
    categoria: "Almacén",
    marca: "Marolio",
    destacado: false,
  },
  {
    id: 5,
    nombre: "Puré de Tomate Marolio 1L",
    precio: 1500,
    precioOferta: 1150,
    emoji: "🍅",
    imagen: PIC("tomate-marolio"),
    categoria: "Almacén",
    marca: "Marolio",
    destacado: false,
  },
  {
    id: 6,
    nombre: "Aceite de Oliva Marolio 500ml",
    precio: 4200,
    precioOferta: 3200,
    emoji: "🫒",
    imagen: PIC("oliva-marolio"),
    categoria: "Almacén",
    marca: "Marolio",
    destacado: false,
  },
  {
    id: 7,
    nombre: "Aceitunas Marolio en Lata 340g",
    precio: 1800,
    precioOferta: 1380,
    emoji: "🫒",
    imagen: PIC("aceitunas-marolio"),
    categoria: "Almacén",
    marca: "Marolio",
    destacado: false,
  },

  // ============ LA SERENÍSIMA ============
  {
    id: 8,
    nombre: "Leche Entera La Serenísima 1L x12",
    precio: 22000,
    precioOferta: 17500,
    emoji: "🥛",
    imagen: PIC("leche-serenisima"),
    categoria: "Almacén",
    marca: "La Serenísima",
    destacado: true,
  },
  {
    id: 9,
    nombre: "Leche Descremada La Serenísima 1L",
    precio: 2100,
    precioOferta: 1620,
    emoji: "🥛",
    imagen: PIC("leche-desc-serenisima"),
    categoria: "Almacén",
    marca: "La Serenísima",
    destacado: false,
  },
  {
    id: 10,
    nombre: "Yogur La Serenísima Entero x4 potes",
    precio: 3200,
    precioOferta: 2400,
    emoji: "🥄",
    imagen: PIC("yogur-serenisima"),
    categoria: "Almacén",
    marca: "La Serenísima",
    destacado: false,
  },
  {
    id: 11,
    nombre: "Queso Cremoso La Serenísima 400g",
    precio: 4500,
    precioOferta: 3400,
    emoji: "🧀",
    imagen: PIC("queso-serenisima"),
    categoria: "Almacén",
    marca: "La Serenísima",
    destacado: false,
  },
  {
    id: 12,
    nombre: "Manteca La Serenísima 200g",
    precio: 2800,
    precioOferta: 2100,
    emoji: "🧈",
    imagen: PIC("manteca-serenisima"),
    categoria: "Almacén",
    marca: "La Serenísima",
    destacado: false,
  },

  // ============ ARCOR ============
  {
    id: 13,
    nombre: "Azúcar Arcor 1kg",
    precio: 1200,
    precioOferta: 920,
    emoji: "🍬",
    imagen: PIC("azucar-arcor"),
    categoria: "Almacén",
    marca: "Arcor",
    destacado: false,
  },
  {
    id: 14,
    nombre: "Galletitas Arcor Surtidas x6 paquetes",
    precio: 3800,
    precioOferta: 2900,
    emoji: "🍪",
    imagen: PIC("galletitas-arcor"),
    categoria: "Almacén",
    marca: "Arcor",
    destacado: true,
  },
  {
    id: 15,
    nombre: "Mermelada Arcor Frutilla 420g",
    precio: 1900,
    precioOferta: 1450,
    emoji: "🍓",
    imagen: PIC("mermelada-arcor"),
    categoria: "Almacén",
    marca: "Arcor",
    destacado: false,
  },
  {
    id: 16,
    nombre: "Caramelos Arcor Surtidos x100 unidades",
    precio: 2500,
    precioOferta: 1900,
    emoji: "🍬",
    imagen: PIC("caramelos-arcor"),
    categoria: "Almacén",
    marca: "Arcor",
    destacado: false,
  },
  {
    id: 17,
    nombre: "Harina Arcor 000 1kg",
    precio: 950,
    precioOferta: 720,
    emoji: "🌾",
    imagen: PIC("harina-arcor"),
    categoria: "Almacén",
    marca: "Arcor",
    destacado: false,
  },

  // ============ COCA-COLA ============
  {
    id: 18,
    nombre: "Coca-Cola 2.25L x6",
    precio: 12000,
    precioOferta: 9200,
    emoji: "🥤",
    imagen: PIC("coca-cola-2l"),
    categoria: "Bebidas",
    marca: "Coca-Cola",
    destacado: true,
  },
  {
    id: 19,
    nombre: "Fanta Naranja 2L x6",
    precio: 11000,
    precioOferta: 8400,
    emoji: "🍊",
    imagen: PIC("fanta-2l"),
    categoria: "Bebidas",
    marca: "Coca-Cola",
    destacado: false,
  },
  {
    id: 20,
    nombre: "Sprite 2L x6",
    precio: 11000,
    precioOferta: 8400,
    emoji: "🍋",
    imagen: PIC("sprite-2l"),
    categoria: "Bebidas",
    marca: "Coca-Cola",
    destacado: false,
  },
  {
    id: 21,
    nombre: "Coca-Cola 500ml x24 unidades",
    precio: 20000,
    precioOferta: 15500,
    emoji: "🥤",
    imagen: PIC("coca-cola-500"),
    categoria: "Bebidas",
    marca: "Coca-Cola",
    destacado: false,
  },
  {
    id: 22,
    nombre: "Schweppes Tónica 1.5L x6",
    precio: 12500,
    precioOferta: 9500,
    emoji: "💧",
    imagen: PIC("schweppes"),
    categoria: "Bebidas",
    marca: "Coca-Cola",
    destacado: false,
  },
  {
    id: 23,
    nombre: "Powerade Naranja 500ml x12",
    precio: 14000,
    precioOferta: 10800,
    emoji: "⚡",
    imagen: PIC("powerade"),
    categoria: "Bebidas",
    marca: "Coca-Cola",
    destacado: false,
  },

  // ============ QUILMES ============
  {
    id: 24,
    nombre: "Cerveza Quilmes 1L x6",
    precio: 15000,
    precioOferta: 11500,
    emoji: "🍺",
    imagen: PIC("quilmes-1l"),
    categoria: "Bebidas",
    marca: "Quilmes",
    destacado: true,
  },
  {
    id: 25,
    nombre: "Cerveza Quilmes Lata 473ml x12",
    precio: 14000,
    precioOferta: 10800,
    emoji: "🍻",
    imagen: PIC("quilmes-lata"),
    categoria: "Bebidas",
    marca: "Quilmes",
    destacado: false,
  },
  {
    id: 26,
    nombre: "Cerveza Quilmes Bock 1L x6",
    precio: 17000,
    precioOferta: 13000,
    emoji: "🍺",
    imagen: PIC("quilmes-bock"),
    categoria: "Bebidas",
    marca: "Quilmes",
    destacado: false,
  },
  {
    id: 27,
    nombre: "Agua Mineral Eco de los Andes 500ml x24",
    precio: 8000,
    precioOferta: 6100,
    emoji: "💧",
    imagen: PIC("agua-quilmes"),
    categoria: "Bebidas",
    marca: "Quilmes",
    destacado: true,
  },

  // ============ UNILEVER (Skip / Comfort / Cif / Dove) ============
  {
    id: 28,
    nombre: "Detergente Skip Líquido 3L",
    precio: 5500,
    precioOferta: 4200,
    emoji: "🧴",
    imagen: PIC("skip-liquido"),
    categoria: "Limpieza",
    marca: "Unilever",
    destacado: true,
  },
  {
    id: 29,
    nombre: "Skip Polvo Matic 3kg",
    precio: 8500,
    precioOferta: 6500,
    emoji: "🧺",
    imagen: PIC("skip-polvo"),
    categoria: "Limpieza",
    marca: "Unilever",
    destacado: false,
  },
  {
    id: 30,
    nombre: "Suavizante Comfort Concentrado 900ml",
    precio: 3200,
    precioOferta: 2450,
    emoji: "👕",
    imagen: PIC("comfort-suavizante"),
    categoria: "Limpieza",
    marca: "Unilever",
    destacado: false,
  },
  {
    id: 31,
    nombre: "Jabón Dove Barra Original x3",
    precio: 3800,
    precioOferta: 2900,
    emoji: "🫧",
    imagen: PIC("dove-jabon"),
    categoria: "Limpieza",
    marca: "Unilever",
    destacado: false,
  },
  {
    id: 32,
    nombre: "Cif Crema Multiusos 500ml",
    precio: 2800,
    precioOferta: 2150,
    emoji: "🧽",
    imagen: PIC("cif-crema"),
    categoria: "Limpieza",
    marca: "Unilever",
    destacado: false,
  },
  {
    id: 33,
    nombre: "Dove Shampoo Nutrición Intensa 400ml",
    precio: 4200,
    precioOferta: 3200,
    emoji: "🚿",
    imagen: PIC("dove-shampoo"),
    categoria: "Limpieza",
    marca: "Unilever",
    destacado: false,
  },

  // ============ AYUDÍN ============
  {
    id: 34,
    nombre: "Lavandina Ayudín Concentrada 1L",
    precio: 1400,
    precioOferta: 1050,
    emoji: "🧪",
    imagen: PIC("ayudin-lavandina"),
    categoria: "Limpieza",
    marca: "Ayudín",
    destacado: false,
  },
  {
    id: 35,
    nombre: "Lavandina Ayudín x12 unidades",
    precio: 15000,
    precioOferta: 11500,
    emoji: "🧪",
    imagen: PIC("ayudin-lavandina-pack"),
    categoria: "Limpieza",
    marca: "Ayudín",
    destacado: true,
  },
  {
    id: 36,
    nombre: "Desengrasante Ayudín Naranja 500ml",
    precio: 2600,
    precioOferta: 1980,
    emoji: "🧽",
    imagen: PIC("ayudin-desengrasante"),
    categoria: "Limpieza",
    marca: "Ayudín",
    destacado: false,
  },
  {
    id: 37,
    nombre: "Limpiador Pisos Ayudín Pino 1L",
    precio: 1900,
    precioOferta: 1450,
    emoji: "🌲",
    imagen: PIC("ayudin-pisos"),
    categoria: "Limpieza",
    marca: "Ayudín",
    destacado: false,
  },
  {
    id: 38,
    nombre: "Limpiavidrios Ayudín 500ml",
    precio: 2100,
    precioOferta: 1600,
    emoji: "🪟",
    imagen: PIC("ayudin-vidrios"),
    categoria: "Limpieza",
    marca: "Ayudín",
    destacado: false,
  },
  {
    id: 39,
    nombre: "Esponjas Ayudín Doble Acción x10",
    precio: 1500,
    precioOferta: 1150,
    emoji: "🧽",
    imagen: PIC("ayudin-esponjas"),
    categoria: "Limpieza",
    marca: "Ayudín",
    destacado: false,
  },
  {
    id: 40,
    nombre: "Papel Higiénico Higienol x12 rollos",
    precio: 2800,
    precioOferta: 2100,
    emoji: "🧻",
    imagen: PIC("papel-higienico"),
    categoria: "Limpieza",
    marca: "Ayudín",
    destacado: false,
  },
];
