export const productsData = [
  // ============ ALMACÉN (5 productos) ============
  {
    id: 1,
    nombre: "Aceite de Girasol Marolio 1.5L",
    precio: 2800,
    precioOferta: 2100,
    emoji: "🫙",
    imagen: require("./assets/aceite.jpeg"),
    categoria: "Almacén",
    marca: "Marolio",
    destacado: true,
  },
  {
    id: 2,
    nombre: "Fideos Spaghetti Marolio 500g",
    precio: 850,
    precioOferta: 640,
    emoji: "🍝",
    imagen: require("./assets/fideos-marolio.webp"),
    categoria: "Almacén",
    marca: "Marolio",
    destacado: false,
  },
  {
    id: 3,
    nombre: "Leche Entera La Serenísima 1L x12",
    precio: 22000,
    precioOferta: 17500,
    emoji: "🥛",
    imagen: require("./assets/leche-serenisima12.webp"),
    categoria: "Almacén",
    marca: "La Serenísima",
    destacado: true,
  },
  {
    id: 4,
    nombre: "Yogur La Serenísima Entero x4 potes",
    precio: 3200,
    precioOferta: 2400,
    emoji: "🥄",
    imagen: require("./assets/yogurt-serenisima4.jpg"),
    categoria: "Almacén",
    marca: "La Serenísima",
    destacado: false,
  },
  {
    id: 5,
    nombre: "Galletitas Arcor Surtidas x6 paquetes",
    precio: 3800,
    precioOferta: 2900,
    emoji: "🍪",
    imagen: require("./assets/galletitas-arcor.webp"),
    categoria: "Almacén",
    marca: "Arcor",
    destacado: true,
  },

  // ============ BEBIDAS (5 productos) ============
  {
    id: 6,
    nombre: "Coca-Cola 2.25L x6",
    precio: 12000,
    precioOferta: 9200,
    emoji: "🥤",
    imagen: require("./assets/coca-6.webp"),
    categoria: "Bebidas",
    marca: "Coca-Cola",
    destacado: true,
  },
  {
    id: 7,
    nombre: "Fanta Naranja 2L x6",
    precio: 11000,
    precioOferta: 8400,
    emoji: "🍊",
    imagen: require("./assets/fanta-6.jpg"),
    categoria: "Bebidas",
    marca: "Coca-Cola",
    destacado: false,
  },
  {
    id: 8,
    nombre: "Sprite 2.25L x6",
    precio: 11000,
    precioOferta: 8400,
    emoji: "🍋",
    imagen: require("./assets/sprite-6-2.25.webp"),
    categoria: "Bebidas",
    marca: "Coca-Cola",
    destacado: false,
  },
  {
    id: 9,
    nombre: "Cerveza Quilmes Lata 473ml x6",
    precio: 15000,
    precioOferta: 11500,
    emoji: "🍺",
    imagen: require("./assets/quilmes-6-473.png"),
    categoria: "Bebidas",
    marca: "Quilmes",
    destacado: true,
  },
  {
    id: 10,
    nombre: "Agua Mineral Eco de los Andes 500ml x24",
    precio: 8000,
    precioOferta: 6100,
    emoji: "💧",
    imagen: require("./assets/agua-mineral-500.webp"),
    categoria: "Bebidas",
    marca: "Quilmes",
    destacado: false,
  },

  // ============ LIMPIEZA (5 productos) ============
  {
    id: 11,
    nombre: "Detergente Skip Líquido 3L",
    precio: 5500,
    precioOferta: 4200,
    emoji: "🧴",
    imagen: require("./assets/detergente-skip-3l.webp"),
    categoria: "Limpieza",
    marca: "Unilever",
    destacado: true,
  },
  {
    id: 12,
    nombre: "Skip Polvo Matic 3kg",
    precio: 8500,
    precioOferta: 6500,
    emoji: "🧺",
    imagen: require("./assets/skip-polvo-3kg.jpg"),
    categoria: "Limpieza",
    marca: "Unilever",
    destacado: false,
  },
  {
    id: 13,
    nombre: "Suavizante Comfort Concentrado 900ml",
    precio: 3200,
    precioOferta: 2450,
    emoji: "👕",
    imagen: require("./assets/comfort-900ml.webp"),
    categoria: "Limpieza",
    marca: "Unilever",
    destacado: false,
  },
  {
    id: 14,
    nombre: "Lavandina Ayudín Concentrada 1L",
    precio: 1400,
    precioOferta: 1050,
    emoji: "🧪",
    imagen: require("./assets/lavandina-ayudin-1l.webp"),
    categoria: "Limpieza",
    marca: "Ayudín",
    destacado: false,
  },
  {
    id: 15,
    nombre: "Limpiavidrios Ayudín 500ml",
    precio: 2100,
    precioOferta: 1600,
    emoji: "🪟",
    imagen: require("./assets/limpiavidrios-500ml.webp"),
    categoria: "Limpieza",
    marca: "Ayudín",
    destacado: true,
  },
];
